### ISSUE TITLE
PvP items availablity in 60 brackets

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/mod-progression-system#103]
In the current bracket (Level 60, pre-MC), https://wowgaming.altervista.org/aowow/?item=19104 is available to Horde, but https://wowgaming.altervista.org/aowow/?item=19103 isn't available for Alliance. This should be equalized, both items seem legit to be available in this bracket.

Also the price needs to be adjusted way upward.

**Comment by Nyeriah** [comment]
I still had that one in my local database so I suppose it was removed in one of those one-time queries we ran. I have readded it, closing this.
