### ISSUE TITLE
[Molten Core] Hands of the Enemy, doesn't let you get more Aqual Quintessence  from Hydraxis

### ISSUE THREAD

**Issue by temperrr** [azerothcore/mod-progression-system#105]
Once a player does Hands of the Enemy, They should  be able to get [one aqual quintessence](https://wowwiki-archive.fandom.com/wiki/Aqual_Quintessence)  from Duke Hydraxis with a gossip option
Once revered, they should be able to get the permanent one https://wowwiki-archive.fandom.com/wiki/Eternal_Quintessence

https://www.youtube.com/watch?v=0oIXSp59hVQ

Once a player does Hands of the Enemy, they get the achievement. I think the achievement should only be obtained when you are getting the essence from Hydraxis.

**Comment by Nyeriah** [comment]
Achievement checks are handled by DBC, it's not a scripted event, just an automatic event once the right criterias are met, so if they get the achievement by completing the quest that is likely correct.

https://github.com/azerothcore/mod-progression-system/commit/bfdee634031b8ac1a82e7014a4011f09e0cb90e2
