### ISSUE TITLE
"Elemental Invasion" Events (1.4 Vanilla)

### ISSUE THREAD

**Issue by ghost** [azerothcore/mod-progression-system#15]
I saw some players farming "Thundering Invaders" in Azshara.

They're not meant to exist in 3.3.5a, I don't think. They're part of a temporary event in a specific classic patch.

The best course of action would be to find out how these events worked, how they triggered, and recreate them as events rather than static NPCs always spawned.

https://classic.wowhead.com/guides/elemental-invasions-wow-classic

https://wotlk.evowow.com/?npc=14462

**Comment by heyitsbench** [comment]
This is wrong. The elemental invasions existed until the Cataclysm revamp.
