### ISSUE TITLE
[BWL Bracket] Lowering the cost of PVP Items

### ISSUE THREAD

**Issue by Hacki95** [azerothcore/mod-progression-system#174]
Once the BWL Bracket releases, we decided to set the prices for PVP Items in the level range of 50-59 (which we previously increased to 20000 honor) to 5000 Honor.

We need the appropriate SQLs for that.

**Comment by FrancescoBorzi** [comment]
It looks like the price has been altered here:

https://github.com/azerothcore/mod-progression-system/blob/main/src/Bracket_50_59_A/sql/world/progression_50_59_a_npc_vendor.sql

and here:

https://github.com/azerothcore/mod-progression-system/blob/main/src/Bracket_50_59_B/sql/world/progression_50_59_b_npc_vendor.sql

not sure if there are others, but it is clearly visible in-game so please double check all PvP vendors in Orgrimmar and Stormwind:

![image](https://user-images.githubusercontent.com/75517/154871939-a8c96b89-cf4b-47a2-9ce5-112d52b7192b.png)

Acceptance criteria:

All 50-59 PvP items which were previously increased (e.g. to 20k honor) should now be set at 5k honor instead.

**Comment by Nefertumm** [comment]
https://github.com/azerothcore/mod-progression-system/pull/180
