### ISSUE TITLE
[PVP Items] Restoration Queries missing

### ISSUE THREAD

**Issue by Hacki95** [azerothcore/mod-progression-system#175]
There seem to be some restoration queries missing for the TBC brackets which restore the 50-59 PVP items to their original prices.

We need the appropriate SQLs for the 61-64 bracket.

**Comment by FrancescoBorzi** [comment]
It looks like the price has been altered here:

https://github.com/azerothcore/mod-progression-system/blob/main/src/Bracket_50_59_A/sql/world/progression_50_59_a_npc_vendor.sql

and here:

https://github.com/azerothcore/mod-progression-system/blob/main/src/Bracket_50_59_B/sql/world/progression_50_59_b_npc_vendor.sql

not sure if there are others, but it is clearly visible in-game so please double check all PvP vendors in Orgrimmar and Stormwind:

![image](https://user-images.githubusercontent.com/75517/154871939-a8c96b89-cf4b-47a2-9ce5-112d52b7192b.png)

Acceptance criteria:

All 50-59 PvP items which were previously increased (e.g. to 20k honor) should now be set at their **original prices** instead.

**Comment by IntelligentQuantum** [comment]
Do you mean the same price that was set in 3.3.5?

**Comment by 55Honey** [comment]
> Do you mean the same price that was set in 3.3.5?

Yes. That should happen in the first bracket after level 60 raids: 61-64
