### ISSUE TITLE
[Feature] Make bracket names clearer

### ISSUE THREAD

**Issue by Samsequel** [azerothcore/mod-progression-system#182]
We would like to rename the brackets in such a way that it is clear what is does.
At this time, you can get very confused and takes a while to know which bracket you need to look at specifically.

examples:
Bracket_50_59_b -> Bracket_50_59_B_UBRS
Bracket_60_1_a -> Bracket_60_1_A_MC

Etcetera.

**Comment by Gultask** [comment]
Done 😁
