### ISSUE TITLE
Bracket_60_1_1 Re-applying the SQL part is invalid.

### ISSUE THREAD

**Issue by zxnhrdz** [azerothcore/mod-progression-system#301]
![98X6}3GZ$JOVO5XXR JDVAV](https://user-images.githubusercontent.com/110412571/217717366-cf33e813-3a67-420b-9c05-92adb0a06fbe.png)

\mod-progression-system\src\Bracket_60_1_1\sql\world\progression_60_1_1_npc_vendor_PvP.sql

/*
  Impact Shell and Wicked Arrow to vendors
  This ammunition was introduced in The Burning Crusade patch 2.5
  items: (28060,28053)
*/

This part can't be applied again. There is no update record in the updates table of az database. The subsequent reapplication cannot continue.

**Comment by Gultask** [comment]
The query looks off but I don't have this problem when setting up the config normally.

Remember that every single bracket up to the one you want must be set to 1. The sole exception being the bracket for the UBRS attunement requirement.

![image](https://user-images.githubusercontent.com/100873791/217963052-b47be722-4de9-4f60-8531-5fb9de75de5b.png)

**Comment by Gultask** [comment]
The DELETE query had nothing to do with the INSERT query. I'll merge the fix soon and you can pull from master
