### ISSUE TITLE
The module cannot be compiled.

### ISSUE THREAD

**Issue by zxnhrdz** [azerothcore/mod-progression-system#306]
Error C2039 "EnterCombat ":not a member of" BossAI "

C3861 “_EnterCombat': Identifier not found.

**Comment by zxnhrdz** [comment]
![076V7QZ6ATLO HH`$)RP9UW](https://user-images.githubusercontent.com/110412571/218660758-1c4c7e55-6939-4ac3-b999-9b2184b88ca4.png)

**Comment by maikale** [comment]
i have the same problem too

**Comment by 55Honey** [comment]
There was a PR merged to AC with an outstanding fix for quite a few modules. Feel free to replace every appearance of `EnterCombat` with ` JustEngagedWith` in all files in `/src/` and provide a PR.

**Comment by zxnhrdz** [comment]
> There was a PR merged to AC with an outstanding fix for quite a few modules. Feel free to replace every appearance of `EnterCombat` with `JustEngagedWith` in all files in `/src/` and provide a PR.

I saw it when I submitted this question, and I just want to remind you that this module needs an update. Thank you again for your reply!

**Comment by Gultask** [comment]
https://github.com/azerothcore/mod-progression-system/pull/307

:)

**Comment by zxnhrdz** [comment]
> #307
> 
> :)

Yes, I personally do the same as you. Thanks again!

**Comment by 55Honey** [comment]
Thanks Gultask!
