### ISSUE TITLE
The module cannot be compiled

### ISSUE THREAD

**Issue by maikale** [azerothcore/mod-progression-system#313]
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "void __cdecl Addmod_progression_system_mainScripts(void)" (?Addmod_progression_system_mainScripts@@YAXXZ) referenced in function "void __cdecl AddModulesScripts(void)" (?AddModulesScripts@@YAXXZ)	worldserver	D:\Azerothcoreprogressive\build\src\server\apps\modules.lib(ModulesLoader.obj)	1	
Error	LNK1120	1 unresolved externals	worldserver	D:\Azerothcoreprogressive\build\bin\RelWithDebInfo\worldserver.exe	1

**Comment by Nyeriah** [comment]
Remove -main from the folder name, as mentioned in the wiki module installation guide page
