### ISSUE TITLE
May I ask: Where should the SQL files and C++script files for progressive modules be placed in the compiled WINDOWS folder? thanks

### ISSUE THREAD

**Issue by feng380** [azerothcore/mod-progression-system#327]
May I ask: Where should the SQL files and C++script files for progressive modules be placed in the compiled WINDOWS folder? thanks

**Comment by 28269890** [comment]
I encountered the same problem.
 SQL cannot load based on the configuration and an error prompt appears: Script named 'npc_brewfest_dungeonmaster' is assigned in the database, but has no code!

**Comment by Nyeriah** [comment]
If you’re using the anticheat, disable anticheat auto update.

**Comment by 28269890** [comment]
After disabling the anticheat, it seems to work fine. Can't both be used at the same time? Also, I didn't find the option for anticheat auto update.

**Comment by feng380** [comment]
> After disabling the anticheat, it seems to work fine. Can't both be used at the same time? Also, I didn't find the option for anticheat auto update.

May I ask where the SQL files for mod on Windows are located and what the directory structure is? Thank you very much!

**Comment by 55Honey** [comment]
You need to place the module in the `/modules/` folder. Make sure you `git clone` this repo right to said folder.
Follow the module installation guide. In short: Re-run cmake and build.
There are examples of scripts and SQL files which will be automatically added depending on the configuration of the progression module.

**Comment by feng380** [comment]
> You need to place the module in the `/modules/` folder. Make sure you `git clone` this repo right to said folder. Follow the module installation guide. In short: Re-run cmake and build. There are examples of scripts and SQL files which will be automatically added depending on the configuration of the progression module.

Does that mean compiling once at a certain bracket?

**Comment by 55Honey** [comment]
No. You set brackets via conf.
