### ISSUE TITLE
SQL missing files

### ISSUE THREAD

**Issue by zxnhrdz** [azerothcore/mod-progression-system#331]
/src/Bracket_61_64/sql/world/progression_61_64_world_event_Ahune.sql

Unable to find

![image](https://github.com/azerothcore/mod-progression-system/assets/110412571/0ac6a546-2567-49bb-ba90-99f55751ade7)

**Comment by Nyeriah** [comment]
This means the file was executed and renamed, as I just renamed it. Not an actual issue. Delete the entry from your `updates`table if you wish it to go away. Closing.
