### ISSUE TITLE
SQL file error

### ISSUE THREAD

**Issue by zxnhrdz** [azerothcore/mod-progression-system#332]
src/Bracket_61_64/sql/world/progression_61_64_world_event_Ahune.sql

src/Bracket_80_1/sql/world/progression_61_64_world_event_Ahune_down.sql

61_64　  SQL file missing
80_1　　SQL file naming error

**Comment by zxnhrdz** [comment]
![image](https://github.com/azerothcore/mod-progression-system/assets/110412571/8dee8c4c-65a3-4421-b40b-5180dcfd008c)


![image](https://github.com/azerothcore/mod-progression-system/assets/110412571/dabdd588-a019-43c6-addc-b5ec1d58b258)

**Comment by 55Honey** [comment]
The files you've mentioned do not exist.
Are you looking for https://github.com/azerothcore/mod-progression-system/pull/330 ?

**Comment by Nyeriah** [comment]
https://github.com/azerothcore/mod-progression-system/issues/331#event-9628110347
