### ISSUE TITLE
[RDF] Remove Random Burning Crusade Dungeon and extend the active levels from Random Classic Dungeon from 57 to 60

### ISSUE THREAD

**Issue by iEmpress** [azerothcore/mod-progression-system#39]
At level 58 you are no longer able to queue for Random Classic Dungeon. Even if Random Burning Crusade Dungeon would not be eligible to be queued, it would be best to extend the levels that Random Classic Dungeon acts in. 

Otherwise, levels 55-57 are the only levels to get the 55 Satchel rewards.

![image](https://user-images.githubusercontent.com/82000605/135351318-d7a9acf3-a984-4d61-ae43-a3ca81e8ca7d.png)

**Comment by Yehonal** [comment]
It should be done via _dbc MySQL table editing by overriding the min level needed for those dungeons
