### ISSUE TITLE
ALLIANCE DK Last Quest <where kings walk> can't see npc ,need add  some code

### ISSUE THREAD

**Issue by leewheel** [azerothcore/mod-progression-system#397]
class npc_ipp_wotlk : public CreatureScript
{
public:
    npc_ipp_wotlk() : CreatureScript("npc_ipp_wotlk") { }

    struct npc_ipp_wotlkAI: ScriptedAI
    {
        explicit npc_ipp_wotlkAI(Creature* creature) : ScriptedAI(creature) { };

        bool CanBeSeen(Player const* player) override
        {
            if (player->IsGameMaster() || !sIndividualProgression->enabled || (player->GetQuestStatus(13188) != QUEST_STATUS_NONE && player->GetQuestStatus(13188) != QUEST_STATUS_REWARDED)) // leewheel 
            {
                return true;
            }
            Player* target = ObjectAccessor::FindConnectedPlayer(player->GetGUID());
            return sIndividualProgression->hasPassedProgression(target, PROGRESSION_TBC_TIER_5);
        }
    };

    CreatureAI* GetAI(Creature* creature) const override
    {
        return new npc_ipp_wotlkAI(creature);
    }
};

**Comment by Nyeriah** [comment]
This is not the individual progression module
