### ISSUE TITLE
Poisoned Water - Removed MC Quest

### ISSUE THREAD

**Issue by Hacki95** [azerothcore/mod-progression-system#53]
For Molten Core we want to re-add the following quest, which needs to be completed before Majodormo Executus can be summoned.

Normally we would want a module for functionality like this, since it needs some modifications for the MC Script this might not be possible though and needs a .patch or something similiar.

Besides that, the quest should still be in the DB. Just deactivated.

We need a patch for the progression system to enable/disable this quest.

https://wowpedia.fandom.com/wiki/Poisoned_Water
https://wowpedia.fandom.com/wiki/The_runes_of_warding

**Comment by Nyeriah** [comment]
We'll need to port the MC script to the progression repo, so this will probably be one of the last few things to be implemented, just so we don't have to keep updating the MC instance file over and over

**Comment by Hacki95** [comment]
All good. We just shouldn't forget about it.
