### ISSUE TITLE
TBC green gems droping while prospecting thorium ore

### ISSUE THREAD

**Issue by gurveleg** [azerothcore/mod-progression-system#57]
Currently TBC green gems still drop from Prospecting thorium. A while ago with the TBC item deletion, the gems were also deleted, but they are still in the prospecting loot table.

The gems in quesiton: (https://wowgaming.altervista.org/aowow/?item=10620#prospecting)
Item 21929, 23077, 23079, 23107, 23112, 23117
Flame Spessarite, Blood Garnet, Deep Peridot, Shadow Draenite, Golden Draenite, Azure Moonstone

They should be removed from Thorium Ore pospecting loot until TBC content is released.

Original Report:  https://github.com/chromiecraft/chromiecraft/issues/2291

**Comment by Buggyswires** [comment]
Confirmed: i got two of those from Prospecting Thorium Ore

![image](https://user-images.githubusercontent.com/43603807/142980823-a92a8372-0ebd-4720-a863-43c602429b03.png)
