### ISSUE TITLE
Disable Pilgrim's bounty

### ISSUE THREAD

**Issue by temperrr** [azerothcore/mod-progression-system#58]
- [ ] Pilgrims Bounty need to be disabled (PR: https://github.com/azerothcore/azerothcore-wotlk/pull/9099)
- [ ] It should not show up in calendar
- [ ] it should be disabled in first bracket
- [ ] it should be re-enabled during wotlk.

**Comment by Yehonal** [comment]
I've had a look and apparently, even though the holidays are in DBC (in order to have the image in the calendar) the dates are handled by the server. Hence, if we do not send the date to the client the event won't be shown.

Maybe the "disables" mechanism could act also on the loading of the event or we can just provide the query to set a 0 date within the game_event table and check if it works

**Comment by temperrr** [comment]
Tested the PR linked, the disable will not hide the event from calendar.

**Comment by Yehonal** [comment]
> Tested the PR linked, the disable will not hide the event from calendar.

can you try to remove the event from the table?

**Comment by temperrr** [comment]
So eh, setting the value of Holiday_Dates of entries 404 to 0, like screenshot, disables it from calendar
![image](https://user-images.githubusercontent.com/20357406/141075947-a0990988-a0e9-4713-9fdd-e50165997661.png)

**Comment by Nyeriah** [comment]
> Tested the PR linked, the disable will not hide the event from calendar.

The disable implementation will now prevent the holiday data from being sent to the client if the associated event is disabled. This, however, requires a relog to take effect, because it seems calendar data is only sent on login and doesn't refresh afterwards.

**Comment by temperrr** [comment]
That would be nice!

**Comment by Nyeriah** [comment]
> That would be nice! so on first login of new char, it displays it ,but after relog no longer?

If you disable the event while the server is running and players are online it won't update it (hide it from their calendars) until the next time they relog, otherwise it's fine and works as expected
