### ISSUE TITLE
[Suggestion] UBRS / LBRS Instance type: Raid

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/mod-progression-system#71]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2328

UBRS / LBRS can be entered although a bossfight is in progress (Drakki)

Tester:
The issue is confirmed. [Blackrock Spire](https://wowgaming.altervista.org/aowow/?zone=1583) is `Instance type: Dungeon`

### Expected Behaviour

Since UBRS is raid `Instance type` should be changed to `Raid`

### Steps to reproduce the problem

Try to walk in to dungeon while your group in fight with boss

### Extra Notes

This type is blizzlike for [Blackrock Spire](https://tbc.wowhead.com/blackrock-spire). Change could be implemented as part of progression mod. In this case need to care about quests and DF. There is could be issues with it. Tbh not worth it.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/03c84db04dd7bce2a8aa5e527aeec2640c6fa7eb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by claudiodfc** [comment]
Shouldn't the players be able to enter Dungeons mid-fights? If no, please provide proof.

**Comment by Shineslippers** [comment]
Players able to enter during fight if instance type is `dungeon`. Suggestion is about to not allow them enter because UBRS is Raid in progression mod. You can't enter `raid` type instances during fight.

**Comment by 55Honey** [comment]
> Shouldn't the players be able to enter Dungeons mid-fights? If no, please provide proof.

Proof is required for being blizz-like, as in PRs/Issues to AC master repo. This is the progression repo. ;-)

On-topic: I'm not sure if that's feasable for LBRS. We're using RDF after all.
