### ISSUE TITLE
Flying Progression Issues

### ISSUE THREAD

**Issue by temperrr** [azerothcore/mod-progression-system#75]
Issue:

When you level up to level 60, you will get a mail from the flying trainer to learn flying at 60. This is not in style of progression, as flying was level 70 in tbc.

Fix:

in the 1-19 bracket, 
make it that the mail will not be send at level 60,
quest can be done at level 70.
and set the level for flying at level 70 
make it that the mail will be send at level 70

at the 71-74 bracket
revert previous changes, so mail get received at 60, quest can be done at 60, training can be done at 60.

**Note:**

It would also be handy that if we decide to put it at an earlier level, that we can easily adjust the script for this. (e.g. we may want flying at level 69 or 68. in the tbc bracket)

**Comment by Nyeriah** [comment]
There are limitations to that table and there already is the epic flight mail being sent at level 70. I've tried moving the mail up but apparently we can only send one mail per level, otherwise we get PK errors (level & racemask I suppose)
